
name: oblig3 workflow

on: [push]

jobs:
  build:
    runs-on: windows-latest
    
    
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Install dependencies
        run: mvn -B package --file pom.xml
        



